#!/usr/bin/env bash
set -euo pipefail

#############################################
# CachyOS Bootstrap Script
# Non-interactive, idempotent system setup
# Requirements: root, paru, Btrfs root
#############################################

# Enable logging to file
exec > >(tee -a /var/log/bootstrap-cachyos.log)
exec 2>&1

#-----------------------------
# System Checks
#-----------------------------

require_root() {
    if [[ "$(id -u)" -ne 0 ]]; then
        echo "ERROR: This script must be run as root (use sudo)." >&2
        exit 1
    fi
}

check_paru() {
    if ! command -v paru >/dev/null 2>&1; then
        echo "ERROR: paru is not installed but is required for AUR packages." >&2
        echo "Install paru first, then re-run this script." >&2
        exit 1
    fi
}

#-----------------------------
# Package Management
#-----------------------------

pacman_install() {
    local pkgs=("$@")
    if ((${#pkgs[@]} > 0)); then
        pacman -Syu --needed --noconfirm "${pkgs[@]}"
    fi
}

paru_install() {
    local pkgs=("$@")
    if ((${#pkgs[@]} > 0)); then
        # Run paru as the actual user (not root) with non-interactive flags
        sudo -u "$SUDO_USER" PARU_PAGER=cat paru -S --needed --noconfirm --skipreview --useask "${pkgs[@]}"
    fi
}

package_installed() {
    pacman -Qi "$1" >/dev/null 2>&1
}

remove_package_if_installed() {
    local pkg="$1"
    if package_installed "$pkg"; then
        echo "Removing $pkg and its dependencies..."
        pacman -Rns --noconfirm "$pkg"
    else
        echo "$pkg not installed, skipping removal."
    fi
}

#-----------------------------
# Snapper Configuration
#-----------------------------

ensure_snapper_root_config() {
    # Create snapper config for root filesystem if it doesn't exist
    if [[ ! -f /etc/snapper/configs/root ]]; then
        echo "Creating snapper config 'root' for / ..."
        snapper -c root create-config /
    else
        echo "Snapper config 'root' already exists."
    fi

    # Enable automatic timeline and cleanup
    systemctl enable --now snapper-timeline.timer snapper-cleanup.timer || true
}

snapshot_exists_by_description() {
    local desc="$1"
    # Exact match on description column to avoid partial matches
    snapper -c root list --columns description | grep -Fxq "$desc"
}

create_protected_snapshot_if_missing() {
    local desc="$1"

    if snapshot_exists_by_description "$desc"; then
        echo "Snapshot '$desc' already exists, skipping."
    else
        echo "Creating protected snapshot: '$desc'"
        snapper -c root create \
            --description "$desc" \
            --cleanup-algorithm important \
            --userdata "important=yes"
    fi
}

#-----------------------------
# GRUB Integration
#-----------------------------

enable_grub_btrfs() {
    # Enable automatic GRUB menu updates when snapshots change
    systemctl enable --now grub-btrfs.path || true
    echo "grub-btrfs.path enabled for automatic snapshot boot entries."
}

#-----------------------------
# OneDrive Setup
#-----------------------------

setup_onedrive() {
    # Configure OneDrive for the actual user (not root)
    local real_user="${SUDO_USER:-}"
    if [[ -z "$real_user" || "$real_user" == "root" ]]; then
        echo "WARNING: Could not determine non-root user for OneDrive."
        echo "Manual setup required - see OneDrive documentation."
        return 0
    fi

    local user_home
    user_home="$(eval echo "~${real_user}")"

    # Create OneDrive config directory
    sudo -u "$real_user" mkdir -p "${user_home}/.config/onedrive"

    # Generate default config if it doesn't exist
    local config_file="${user_home}/.config/onedrive/config"
    if [[ ! -f "$config_file" ]]; then
        cat <<EOF | sudo -u "$real_user" tee "$config_file" >/dev/null
# OneDrive configuration (abraunegg client)
# Generated by bootstrap-cachyos.sh

sync_dir = "${user_home}/OneDrive"
skip_symlinks = "true"
monitor_interval = "300"
EOF
    fi

    # Enable user services to run without active login
    loginctl enable-linger "$real_user" || true

    # Enable OneDrive systemd user service
    sudo -u "$real_user" systemctl --user enable --now onedrive.service || true

    cat <<'EOF'

╔════════════════════════════════════════════════════════════╗
║          OneDrive Manual Authentication Required           ║
╚════════════════════════════════════════════════════════════╝

Log in as your regular user and complete these steps ONCE:

1. Run: onedrive
2. Open the URL shown in your browser
3. Sign in to Microsoft and authorize the app
4. Paste the response URL back into the terminal
5. Restart the service: systemctl --user restart onedrive.service

OneDrive will then sync automatically via systemd.

EOF
}

#-----------------------------
# Main Execution
#-----------------------------

main() {
    require_root
    check_paru

    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║          CachyOS Bootstrap - Corporate Image Setup         ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo "Log: /var/log/bootstrap-cachyos.log"
    echo ""

    echo "==> Installing base packages (pacman)"
    pacman_install snapper steam libreoffice-fresh grub-btrfs mc

    echo ""
    echo "==> Installing AUR packages (paru)"
    paru_install microsoft-edge-stable-bin google-chrome impression onedrive-abraunegg

    echo ""
    echo "==> Configuring Snapper for root filesystem"
    ensure_snapper_root_config

    echo ""
    echo "==> Creating initial protected snapshot"
    create_protected_snapshot_if_missing "Base CachyOS install+snapper - important keep forever!"

    echo ""
    echo "==> Removing Firefox"
    remove_package_if_installed firefox

    echo ""
    echo "==> Enabling GRUB snapshot integration"
    enable_grub_btrfs

    echo ""
    echo "==> Configuring OneDrive sync"
    setup_onedrive

    echo ""
    echo "==> Creating final protected snapshot"
    create_protected_snapshot_if_missing "Base CachyOS Complete - Let the chaos begin!"

    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║                    Bootstrap Complete!                     ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    echo "System will reboot in 60 seconds."
    echo "Press Ctrl+C to cancel and review logs."
    echo ""

    for i in {60..1}; do
        printf "\r⏳ Rebooting in %2d seconds..." "$i"
        sleep 1
    done
    echo ""
    systemctl reboot
}

main "$@"
